;;; org-bleve-index-test.el --- Tests for org-bleve-index -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'org)
(require 'org-bleve-index)

(defmacro org-bleve-index-test--with-clean-state (&rest body)
  `(let ((org-mode-hook org-mode-hook))
     (unwind-protect
         (progn
           (clrhash org-bleve-index--inflight-update-processes)
           (clrhash org-bleve-index--pending-update-requests)
           (when (get-buffer org-bleve-index-diagnostics-buffer)
             (kill-buffer org-bleve-index-diagnostics-buffer))
           ,@body)
       (clrhash org-bleve-index--inflight-update-processes)
       (clrhash org-bleve-index--pending-update-requests)
       (when (get-buffer org-bleve-index-diagnostics-buffer)
         (kill-buffer org-bleve-index-diagnostics-buffer))
       (org-bleve-index-mode -1))))

(defmacro org-bleve-index-test--with-dummy-process (binding &rest body)
  (declare (indent 1))
  (let ((process-var (car binding)))
    `(let* ((buffer (generate-new-buffer " *org-bleve-index-test*"))
            (,process-var (start-process "org-bleve-index-test" buffer "cat")))
       (set-process-query-on-exit-flag ,process-var nil)
       (unwind-protect
           (progn ,@body)
         (when (process-live-p ,process-var)
           (delete-process ,process-var))
         (when (buffer-live-p buffer)
           (kill-buffer buffer))))))

(ert-deftest org-bleve-index-command-args-use-json-and-config ()
  (let ((org-bleve-index-config-file "~/org-search/config.txtpb"))
    (should (equal (org-bleve-index--command-args "update-file" '("/tmp/file.org"))
                   (list "--json"
                         "--config"
                         (expand-file-name org-bleve-index-config-file)
                         "update-file"
                         "/tmp/file.org")))))

(ert-deftest org-bleve-index-command-args-omit-config-when-unset ()
  (let ((org-bleve-index-config-file nil))
    (should (equal (org-bleve-index--command-args "rebuild" nil)
                   '("--json" "rebuild")))))

(ert-deftest org-bleve-index-update-buffer-starts-update-command ()
  (with-temp-buffer
    (org-mode)
    (setq-local buffer-file-name "/tmp/test.org")
    (cl-letf (((symbol-function 'org-bleve-index--request-update)
               (lambda (path silent-success)
                 (should (equal path "/tmp/test.org"))
                 (should-not silent-success)
                 'process)))
      (should (eq (org-bleve-index-update-buffer) 'process)))))

(ert-deftest org-bleve-index-update-buffer-requires-file-backed-org-buffer ()
  (with-temp-buffer
    (org-mode)
    (should-error (org-bleve-index-update-buffer) :type 'user-error))
  (with-temp-buffer
    (setq-local buffer-file-name "/tmp/test.txt")
    (should-error (org-bleve-index-update-buffer) :type 'user-error)))

(ert-deftest org-bleve-index-rebuild-starts-rebuild-command ()
  (cl-letf (((symbol-function 'org-bleve-index--start-command)
             (lambda (subcommand arguments silent-success)
               (should (equal subcommand "rebuild"))
               (should-not arguments)
               (should-not silent-success)
               'process)))
    (should (eq (org-bleve-index-rebuild) 'process))))

(ert-deftest org-bleve-index-mode-installs-buffer-local-after-save-hooks ()
  (org-bleve-index-test--with-clean-state
   (with-temp-buffer
     (org-mode)
     (org-bleve-index-mode 1)
     (should (memq #'org-bleve-index--enable-current-buffer org-mode-hook))
     (should (memq #'org-bleve-index--after-save after-save-hook))
     (org-bleve-index-mode -1)
     (should-not (memq #'org-bleve-index--enable-current-buffer org-mode-hook))
     (should-not (memq #'org-bleve-index--after-save after-save-hook)))))

(ert-deftest org-bleve-index-mode-installs-hook-for-future-org-buffers ()
  (org-bleve-index-test--with-clean-state
   (org-bleve-index-mode 1)
   (with-temp-buffer
     (org-mode)
     (should (memq #'org-bleve-index--after-save after-save-hook)))))

(ert-deftest org-bleve-index-after-save-starts-update-for-org-file-buffers ()
  (with-temp-buffer
    (org-mode)
    (setq-local buffer-file-name "/tmp/test.org")
    (let ((org-bleve-index-mode t)
          (org-bleve-index-auto-sync t))
      (cl-letf (((symbol-function 'org-bleve-index--request-update)
                 (lambda (path silent-success)
                   (should (equal path "/tmp/test.org"))
                   (should silent-success)
                   'started)))
        (should (eq (org-bleve-index--after-save) 'started))))))

(ert-deftest org-bleve-index-after-save-ignores-buffers-without-file-or-disabled-sync ()
  (with-temp-buffer
    (org-mode)
    (let ((org-bleve-index-mode t)
          (org-bleve-index-auto-sync t)
          (called nil))
      (cl-letf (((symbol-function 'org-bleve-index--request-update)
                 (lambda (_path _silent-success)
                   (setq called t))))
        (org-bleve-index--after-save)
        (should-not called))))
  (with-temp-buffer
    (org-mode)
    (setq-local buffer-file-name "/tmp/test.org")
    (let ((org-bleve-index-mode t)
          (org-bleve-index-auto-sync nil)
          (called nil))
      (cl-letf (((symbol-function 'org-bleve-index--request-update)
                 (lambda (_path _silent-success)
                   (setq called t))))
        (org-bleve-index--after-save)
        (should-not called)))))

(ert-deftest org-bleve-index-request-update-starts-immediately-without-inflight-process ()
  (org-bleve-index-test--with-clean-state
   (cl-letf (((symbol-function 'org-bleve-index--start-update-process)
              (lambda (path silent-success)
                (should (equal path "/tmp/test.org"))
                (should silent-success)
                'process)))
     (should (eq (org-bleve-index--request-update "/tmp/test.org" t) 'process)))))

(ert-deftest org-bleve-index-request-update-queues-when-process-is-inflight ()
  (org-bleve-index-test--with-clean-state
   (puthash "/tmp/test.org" 'running org-bleve-index--inflight-update-processes)
   (cl-letf (((symbol-function 'org-bleve-index--start-update-process)
              (lambda (_path _silent-success)
                (ert-fail "should not start a second concurrent update process"))))
     (should (eq (org-bleve-index--request-update "/tmp/test.org" t) 'queued))
     (should (equal (gethash "/tmp/test.org" org-bleve-index--pending-update-requests)
                    '(:silent-success t))))))

(ert-deftest org-bleve-index-request-update-coalesces-queued-reruns-per-file-path ()
  (org-bleve-index-test--with-clean-state
   (puthash "/tmp/test.org" 'running org-bleve-index--inflight-update-processes)
   (org-bleve-index--request-update "/tmp/test.org" t)
   (org-bleve-index--request-update "/tmp/test.org" nil)
   (should (equal (gethash "/tmp/test.org" org-bleve-index--pending-update-requests)
                  '(:silent-success nil)))))

(ert-deftest org-bleve-index-drain-pending-update-starts-one-rerun-and-clears-queue ()
  (org-bleve-index-test--with-clean-state
   (puthash "/tmp/test.org" '(:silent-success nil) org-bleve-index--pending-update-requests)
   (cl-letf (((symbol-function 'org-bleve-index--start-update-process)
              (lambda (path silent-success)
                (should (equal path "/tmp/test.org"))
                (should-not silent-success)
                'rerun-process)))
     (should (eq (org-bleve-index--drain-pending-update "/tmp/test.org") 'rerun-process))
     (should-not (gethash "/tmp/test.org" org-bleve-index--pending-update-requests)))))

(ert-deftest org-bleve-index-handle-success-keeps-update-file-quiet-by-default ()
  (org-bleve-index-test--with-clean-state
   (org-bleve-index-test--with-dummy-process (process)
    (process-put process 'org-bleve-index-subcommand "update-file")
    (process-put process 'org-bleve-index-silent-success nil)
    (with-current-buffer (process-buffer process)
      (insert "{\"status\":\"updated\",\"path\":\"/tmp/test.org\",\"indexed_entry_count\":1}\n"))
    (let (messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (org-bleve-index--handle-success process)
        (should-not messages))))))

(ert-deftest org-bleve-index-handle-success-reports-manual-rebuilds ()
  (org-bleve-index-test--with-clean-state
   (org-bleve-index-test--with-dummy-process (process)
    (process-put process 'org-bleve-index-subcommand "rebuild")
    (process-put process 'org-bleve-index-silent-success nil)
    (with-current-buffer (process-buffer process)
      (insert "{\"indexed_file_count\":2,\"indexed_entry_count\":3}\n"))
    (let (messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (org-bleve-index--handle-success process)
        (should (equal messages '("org-bleve-index: rebuild finished (2 files, 3 entries)"))))))))

(ert-deftest org-bleve-index-handle-failure-renders-grouped-duplicate-diagnostics ()
  (org-bleve-index-test--with-clean-state
   (org-bleve-index-test--with-dummy-process (process)
    (process-put process 'org-bleve-index-subcommand "update-file")
    (process-put process 'org-bleve-index-args '("--json" "update-file" "/tmp/test.org"))
    (with-current-buffer (process-buffer process)
      (insert "{\"error\":\"found 2 duplicate org IDs\",\"duplicates\":[{\"id\":\"another-id\",\"occurrences\":[{\"path\":\"/notes/one.org\",\"headline\":\"One\"},{\"path\":\"/notes/two.org\",\"headline\":\"Two\"}]},{\"id\":\"shared-id\",\"occurrences\":[{\"path\":\"/notes/three.org\",\"headline\":\"Three\"}]}]}\n"))
    (let (messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (org-bleve-index--handle-failure process)
        (should (equal messages '("org-bleve-index: duplicate Org IDs; see *org-bleve-index*")))))
    (with-current-buffer (org-bleve-index--diagnostics-buffer)
      (let ((text (buffer-string)))
        (should (string-match-p "update-file: duplicate Org IDs" text))
        (should (string-match-p "Command: org-search --json update-file /tmp/test.org" text))
        (should (string-match-p "Summary: found 2 duplicate org IDs" text))
        (should (string-match-p "- another-id" text))
        (should (string-match-p "  - /notes/one.org: One" text))
        (should (string-match-p "  - /notes/two.org: Two" text))
        (should (string-match-p "- shared-id" text))
        (should (string-match-p "  - /notes/three.org: Three" text)))))))

(ert-deftest org-bleve-index-start-command-records-start-errors-in-diagnostics-buffer ()
  (org-bleve-index-test--with-clean-state
   (let ((org-bleve-index-command "/definitely/missing/org-search")
         messages)
     (cl-letf (((symbol-function 'message)
                (lambda (format-string &rest args)
                  (push (apply #'format format-string args) messages))))
       (should-not (org-bleve-index--start-command "rebuild" nil nil))
       (should (equal messages '("org-bleve-index: failed to start rebuild; see *org-bleve-index*")))))
   (with-current-buffer (org-bleve-index--diagnostics-buffer)
     (let ((text (buffer-string)))
       (should (string-match-p "rebuild: failed to start" text))
       (should (string-match-p "Command: /definitely/missing/org-search --json rebuild" text))
       (should (string-match-p "Error:" text))))))

(ert-deftest org-bleve-index-handle-success-records-malformed-json-diagnostics ()
  (org-bleve-index-test--with-clean-state
   (org-bleve-index-test--with-dummy-process (process)
    (process-put process 'org-bleve-index-subcommand "update-file")
    (process-put process 'org-bleve-index-args '("--json" "update-file" "/tmp/test.org"))
    (with-current-buffer (process-buffer process)
      (insert "not-json\n"))
    (let (messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (org-bleve-index--handle-success process)
        (should (equal messages '("org-bleve-index: malformed JSON from update-file; see *org-bleve-index*")))))
    (with-current-buffer (org-bleve-index--diagnostics-buffer)
      (let ((text (buffer-string)))
        (should (string-match-p "update-file: malformed JSON response" text))
        (should (string-match-p "Command: org-search --json update-file /tmp/test.org" text))
        (should (string-match-p "Raw output:" text))
        (should (string-match-p "not-json" text)))))))

;;; org-bleve-index-test.el ends here
