;;; recall-org-roam-test.el --- Tests for recall-org-roam -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'org)
(require 'recall-org-roam)

(defmacro recall-org-roam-test--with-clean-state (&rest body)
  `(let ((org-mode-hook org-mode-hook))
     (unwind-protect
         (progn
           (clrhash recall-org-roam--inflight-update-processes)
           (clrhash recall-org-roam--pending-update-requests)
           (when (get-buffer recall-org-roam-diagnostics-buffer)
             (kill-buffer recall-org-roam-diagnostics-buffer))
           ,@body)
       (clrhash recall-org-roam--inflight-update-processes)
       (clrhash recall-org-roam--pending-update-requests)
       (when (get-buffer recall-org-roam-diagnostics-buffer)
         (kill-buffer recall-org-roam-diagnostics-buffer))
       (recall-org-roam-mode -1))))

(defmacro recall-org-roam-test--with-dummy-process (binding &rest body)
  (declare (indent 1))
  (let ((process-var (car binding)))
    `(let* ((buffer (generate-new-buffer " *recall-org-roam-test*"))
            (,process-var (start-process "recall-org-roam-test" buffer "cat")))
       (set-process-query-on-exit-flag ,process-var nil)
       (unwind-protect
           (progn ,@body)
         (when (process-live-p ,process-var)
           (delete-process ,process-var))
         (when (buffer-live-p buffer)
           (kill-buffer buffer))))))

(ert-deftest recall-org-roam-command-args-use-json-and-config ()
  (let ((recall-org-roam-config-file "~/recall-org-roam/config.txtpb"))
    (should (equal (recall-org-roam--command-args "update-file" '("/tmp/file.org"))
                   (list "--json"
                         "--config"
                         (expand-file-name recall-org-roam-config-file)
                         "update-file"
                         "/tmp/file.org")))))

(ert-deftest recall-org-roam-command-args-omit-config-when-unset ()
  (let ((recall-org-roam-config-file nil))
    (should (equal (recall-org-roam--command-args "rebuild" nil)
                   '("--json" "rebuild")))))

(ert-deftest recall-org-roam-update-buffer-starts-update-command ()
  (with-temp-buffer
    (org-mode)
    (setq-local buffer-file-name "/tmp/test.org")
    (cl-letf (((symbol-function 'recall-org-roam--request-update)
               (lambda (path silent-success)
                 (should (equal path "/tmp/test.org"))
                 (should-not silent-success)
                 'process)))
      (should (eq (recall-org-roam-update-buffer) 'process)))))

(ert-deftest recall-org-roam-update-buffer-requires-file-backed-org-buffer ()
  (with-temp-buffer
    (org-mode)
    (should-error (recall-org-roam-update-buffer) :type 'user-error))
  (with-temp-buffer
    (setq-local buffer-file-name "/tmp/test.txt")
    (should-error (recall-org-roam-update-buffer) :type 'user-error)))

(ert-deftest recall-org-roam-rebuild-starts-rebuild-command ()
  (cl-letf (((symbol-function 'recall-org-roam--start-command)
             (lambda (subcommand arguments silent-success)
               (should (equal subcommand "rebuild"))
               (should-not arguments)
               (should-not silent-success)
               'process)))
    (should (eq (recall-org-roam-rebuild) 'process))))

(ert-deftest recall-org-roam-mode-installs-buffer-local-after-save-hooks ()
  (recall-org-roam-test--with-clean-state
   (with-temp-buffer
     (org-mode)
     (recall-org-roam-mode 1)
     (should (memq #'recall-org-roam--enable-current-buffer org-mode-hook))
     (should (memq #'recall-org-roam--after-save after-save-hook))
     (recall-org-roam-mode -1)
     (should-not (memq #'recall-org-roam--enable-current-buffer org-mode-hook))
     (should-not (memq #'recall-org-roam--after-save after-save-hook)))))

(ert-deftest recall-org-roam-mode-installs-hook-for-future-org-buffers ()
  (recall-org-roam-test--with-clean-state
   (recall-org-roam-mode 1)
   (with-temp-buffer
     (org-mode)
     (should (memq #'recall-org-roam--after-save after-save-hook)))))

(ert-deftest recall-org-roam-after-save-starts-update-for-org-file-buffers ()
  (with-temp-buffer
    (org-mode)
    (setq-local buffer-file-name "/tmp/test.org")
    (let ((recall-org-roam-mode t)
          (recall-org-roam-auto-sync t))
      (cl-letf (((symbol-function 'recall-org-roam--request-update)
                 (lambda (path silent-success)
                   (should (equal path "/tmp/test.org"))
                   (should silent-success)
                   'started)))
        (should (eq (recall-org-roam--after-save) 'started))))))

(ert-deftest recall-org-roam-after-save-ignores-buffers-without-file-or-disabled-sync ()
  (with-temp-buffer
    (org-mode)
    (let ((recall-org-roam-mode t)
          (recall-org-roam-auto-sync t)
          (called nil))
      (cl-letf (((symbol-function 'recall-org-roam--request-update)
                 (lambda (_path _silent-success)
                   (setq called t))))
        (recall-org-roam--after-save)
        (should-not called))))
  (with-temp-buffer
    (org-mode)
    (setq-local buffer-file-name "/tmp/test.org")
    (let ((recall-org-roam-mode t)
          (recall-org-roam-auto-sync nil)
          (called nil))
      (cl-letf (((symbol-function 'recall-org-roam--request-update)
                 (lambda (_path _silent-success)
                   (setq called t))))
        (recall-org-roam--after-save)
        (should-not called)))))

(ert-deftest recall-org-roam-request-update-starts-immediately-without-inflight-process ()
  (recall-org-roam-test--with-clean-state
   (cl-letf (((symbol-function 'recall-org-roam--start-update-process)
              (lambda (path silent-success)
                (should (equal path "/tmp/test.org"))
                (should silent-success)
                'process)))
     (should (eq (recall-org-roam--request-update "/tmp/test.org" t) 'process)))))

(ert-deftest recall-org-roam-request-update-queues-when-process-is-inflight ()
  (recall-org-roam-test--with-clean-state
   (puthash "/tmp/test.org" 'running recall-org-roam--inflight-update-processes)
   (cl-letf (((symbol-function 'recall-org-roam--start-update-process)
              (lambda (_path _silent-success)
                (ert-fail "should not start a second concurrent update process"))))
     (should (eq (recall-org-roam--request-update "/tmp/test.org" t) 'queued))
     (should (equal (gethash "/tmp/test.org" recall-org-roam--pending-update-requests)
                    '(:silent-success t))))))

(ert-deftest recall-org-roam-request-update-coalesces-queued-reruns-per-file-path ()
  (recall-org-roam-test--with-clean-state
   (puthash "/tmp/test.org" 'running recall-org-roam--inflight-update-processes)
   (recall-org-roam--request-update "/tmp/test.org" t)
   (recall-org-roam--request-update "/tmp/test.org" nil)
   (should (equal (gethash "/tmp/test.org" recall-org-roam--pending-update-requests)
                  '(:silent-success nil)))))

(ert-deftest recall-org-roam-drain-pending-update-starts-one-rerun-and-clears-queue ()
  (recall-org-roam-test--with-clean-state
   (puthash "/tmp/test.org" '(:silent-success nil) recall-org-roam--pending-update-requests)
   (cl-letf (((symbol-function 'recall-org-roam--start-update-process)
              (lambda (path silent-success)
                (should (equal path "/tmp/test.org"))
                (should-not silent-success)
                'rerun-process)))
     (should (eq (recall-org-roam--drain-pending-update "/tmp/test.org") 'rerun-process))
     (should-not (gethash "/tmp/test.org" recall-org-roam--pending-update-requests)))))

(ert-deftest recall-org-roam-handle-success-keeps-update-file-quiet-by-default ()
  (recall-org-roam-test--with-clean-state
   (recall-org-roam-test--with-dummy-process (process)
    (process-put process 'recall-org-roam-subcommand "update-file")
    (process-put process 'recall-org-roam-silent-success nil)
    (with-current-buffer (process-buffer process)
      (insert "{\"status\":\"updated\",\"path\":\"/tmp/test.org\",\"indexed_entry_count\":1}\n"))
    (let (messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (recall-org-roam--handle-success process)
        (should-not messages))))))

(ert-deftest recall-org-roam-handle-success-reports-manual-rebuilds ()
  (recall-org-roam-test--with-clean-state
   (recall-org-roam-test--with-dummy-process (process)
    (process-put process 'recall-org-roam-subcommand "rebuild")
    (process-put process 'recall-org-roam-silent-success nil)
    (with-current-buffer (process-buffer process)
      (insert "{\"indexed_file_count\":2,\"indexed_entry_count\":3}\n"))
    (let (messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (recall-org-roam--handle-success process)
        (should (equal messages '("recall-org-roam: rebuild finished (2 files, 3 entries)"))))))))

(ert-deftest recall-org-roam-handle-failure-renders-grouped-duplicate-diagnostics ()
  (recall-org-roam-test--with-clean-state
   (recall-org-roam-test--with-dummy-process (process)
    (process-put process 'recall-org-roam-subcommand "update-file")
    (process-put process 'recall-org-roam-args '("--json" "update-file" "/tmp/test.org"))
    (with-current-buffer (process-buffer process)
      (insert "{\"error\":\"found 2 duplicate org IDs\",\"duplicates\":[{\"id\":\"another-id\",\"occurrences\":[{\"path\":\"/notes/one.org\",\"headline\":\"One\"},{\"path\":\"/notes/two.org\",\"headline\":\"Two\"}]},{\"id\":\"shared-id\",\"occurrences\":[{\"path\":\"/notes/three.org\",\"headline\":\"Three\"}]}]}\n"))
    (let (messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (recall-org-roam--handle-failure process)
        (should (equal messages '("recall-org-roam: duplicate Org IDs; see *recall-org-roam*")))))
    (with-current-buffer (recall-org-roam--diagnostics-buffer)
      (let ((text (buffer-string)))
        (should (string-match-p "update-file: duplicate Org IDs" text))
        (should (string-match-p "Command: recall-org-roam --json update-file /tmp/test.org" text))
        (should (string-match-p "Summary: found 2 duplicate org IDs" text))
        (should (string-match-p "- another-id" text))
        (should (string-match-p "  - /notes/one.org: One" text))
        (should (string-match-p "  - /notes/two.org: Two" text))
        (should (string-match-p "- shared-id" text))
        (should (string-match-p "  - /notes/three.org: Three" text)))))))

(ert-deftest recall-org-roam-start-command-records-start-errors-in-diagnostics-buffer ()
  (recall-org-roam-test--with-clean-state
   (let ((recall-org-roam-command "/definitely/missing/recall-org-roam")
         messages)
     (cl-letf (((symbol-function 'message)
                (lambda (format-string &rest args)
                  (push (apply #'format format-string args) messages))))
       (should-not (recall-org-roam--start-command "rebuild" nil nil))
       (should (equal messages '("recall-org-roam: failed to start rebuild; see *recall-org-roam*")))))
   (with-current-buffer (recall-org-roam--diagnostics-buffer)
     (let ((text (buffer-string)))
       (should (string-match-p "rebuild: failed to start" text))
       (should (string-match-p "Command: /definitely/missing/recall-org-roam --json rebuild" text))
       (should (string-match-p "Error:" text))))))

(ert-deftest recall-org-roam-handle-success-records-malformed-json-diagnostics ()
  (recall-org-roam-test--with-clean-state
   (recall-org-roam-test--with-dummy-process (process)
    (process-put process 'recall-org-roam-subcommand "update-file")
    (process-put process 'recall-org-roam-args '("--json" "update-file" "/tmp/test.org"))
    (with-current-buffer (process-buffer process)
      (insert "not-json\n"))
    (let (messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (recall-org-roam--handle-success process)
        (should (equal messages '("recall-org-roam: malformed JSON from update-file; see *recall-org-roam*")))))
    (with-current-buffer (recall-org-roam--diagnostics-buffer)
      (let ((text (buffer-string)))
        (should (string-match-p "update-file: malformed JSON response" text))
        (should (string-match-p "Command: recall-org-roam --json update-file /tmp/test.org" text))
        (should (string-match-p "Raw output:" text))
        (should (string-match-p "not-json" text)))))))

;;; recall-org-roam-test.el ends here
